### PR TITLE
Started working on this now.

### PR DESCRIPTION
**Pull request by nicklasb**
Started with some general cleanup; my goal in this branch is the following:
1. Making a standalone demo without external dependencies(perhaps loading from a JSON-file)
2. Moving settings out of schema and into form.
3. Improve test coverage.

### CODE REVIEW

**Comment by nicklasb** [comment]
Oh, and: 
4. Create a callback function instead of having things loaded in the forms

**Comment by stevehu** [comment]
Great. They are all nice ideas and I can wait to see the outcome. I am focusing on the Light Framework on API creation, security and management these days and your help is much appreciated.

**Comment by nicklasb** [comment]
Ok, no problem, hopefully I can use it in my own stuff then, too. 
With regards to that, I will remove the Light references and only use some JSON backend, however it would be good to add links to an example implementation of one or more backend, such as light, for example..

**Comment by nicklasb** [comment]
Hi, 
I am now done with the rewrite.
There are two more things I'd like to do:
1. There is after the rewrite only a synchrous callback, which is kind of crap, I will add an async variant soon. 
2. I saw that you had a light server running, somewhere? When I have made the async callbac variant, perhaps one example could be connected to it?

**Comment by stevehu** [comment]
Yes. I have some apis but they are all authorized based on roles. I will create one for your demo and every can access freely. Let me know what list of item you want and i can even give you an api to update it to reflect the dynamic features

Thanks,

Steve

Sent from my Sony Xperia™ smartphone

---- Nicklas Börjesson wrote ----

**Comment by nicklasb** [comment]
Ok. I have now done the async stuff. 
I don't know, look at the demo as it is now (hopefully the url to the testdata.json file works for you as well). You can give it what you like.

Well thank *you*, I wouldn't have a proper dropdown if you hadn't started.  :-)

**Comment by nicklasb** [comment]
Hi, I will probably do some more stuff, however I would lite to make a bower-release soon, so others can use it, give feedback and commit, will you be having any time to help out on that?  

If not, there are two options:
1. You give me commit access to this repository
2. I basically take over the project, we deprecate this repo, I stop hassling you with pull requests and we make mine the main repo and I give you commit access. Of course you will continue to be credited and so forth.

**Comment by stevehu** [comment]
Hi Nicklas,

I have created a dev team and invite you to join. Once you've joined, you
should have admin access to the repo. You are the owner of it and you can
even invite others to join.

Your code is more generic and will be helpful for a lot of folks.

Thanks a lot for your contribution.

Steve

**Comment by nicklasb** [comment]
Great!

**Comment by stevehu** [comment]
Just one more thing to clarify. The original code is not mine and I just
forked from

https://github.com/chengz/schema-form-strapselect

Please update the readme and license to credit the origin author.

Thanks,

Steve

**Comment by nicklasb** [comment]
Oh, I did not see that. However, that project doesn't have any dynamic updating of content. Why isn't this a fork of that project?

**Comment by stevehu** [comment]
I am new to github and didnot even know how to folk then:-) 

Sent from my Sony Xperia™ smartphone

---- Nicklas Börjesson wrote ----

**Comment by nicklasb** [comment]
Haha, ok. I'll better get in touch with the original author then. The correct and must rigteous approach here would then be to merge the projects in some way, as he seems to have put some effort into documentation and so forth.

**Comment by stevehu** [comment]
I agree. You should fork the original as my version is just used in my framework and not generic.

Thanks,

Steve

Sent from my Sony Xperia™ smartphone

---- Nicklas Börjesson wrote ----

**Comment by nicklasb** [comment]
I will do that, I'll just have a chat with the author first.

**Comment by nicklasb** [comment]
I merged the repos (gotta love GIT) and made a monstrous pull request. :-)
https://github.com/chengz/schema-form-strapselect/pull/2

**Comment by nicklasb** [comment]
Ok, I have spoken to him, and he is in the same situation as you are, so I will continue with my own repository. 

I will after adding tests and docs probably make some more significant changes, as including ui-select support into the same codebase. I really like the look of those.

**Pull request closed without merging**
